'use client';
import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Save, UserRound, Briefcase, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';

export default function ProfileClient({ profile, userId, email }: { profile: any; userId: string; email: string }) {
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ full_name: profile?.full_name ?? '', title: profile?.title ?? '', company: profile?.company ?? '', bio: profile?.bio ?? '', linkedin_url: profile?.linkedin_url ?? '', github_url: profile?.github_url ?? '' });
  const update = (name: keyof typeof form, value: string) => setForm((current) => ({ ...current, [name]: value }));
  async function save() { setSaving(true); const { error } = await createClient().from('profiles').update({ ...form, updated_at: new Date().toISOString() }).eq('id', userId); setSaving(false); error ? toast.error(error.message) : toast.success('Profile saved successfully'); }
  const Field = ({ label, name, placeholder }: { label: string; name: keyof typeof form; placeholder: string }) => <label className="block text-xs font-semibold" style={{ color: 'var(--text-secondary)' }}>{label}<input className="input-dark mt-1.5" value={form[name]} onChange={(e) => update(name, e.target.value)} placeholder={placeholder} /></label>;
  return <div className="max-w-4xl mx-auto space-y-6 animate-fade-up"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-3xl font-black text-white">Your profile</h1><p className="mt-1">Manage the information mentors see when you book a session.</p></div><button onClick={save} disabled={saving} className="btn-neon-green self-start">{saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}{saving ? 'Saving…' : 'Save changes'}</button></div><div className="grid lg:grid-cols-3 gap-5"><aside className="card p-6 h-fit text-center"><div className="w-20 h-20 rounded-2xl mx-auto flex items-center justify-center text-2xl font-bold" style={{ background: 'linear-gradient(135deg,var(--neon-green),var(--neon-cyan))', color: '#07100d' }}>{(form.full_name || email || 'U')[0].toUpperCase()}</div><h2 className="text-lg font-bold text-white mt-4">{form.full_name || 'Your name'}</h2><p className="text-xs mt-1">{email}</p></aside><div className="lg:col-span-2 space-y-5"><section className="card p-6 space-y-4"><h2 className="font-bold text-white flex items-center gap-2"><UserRound className="w-5 h-5 text-neon-green" /> Personal details</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="Full name" name="full_name" placeholder="Your full name" /><label className="block text-xs font-semibold" style={{ color: 'var(--text-secondary)' }}>Email address<input className="input-dark mt-1.5 opacity-60" value={email} disabled /></label><Field label="Job title" name="title" placeholder="e.g. Frontend Developer" /><Field label="Company" name="company" placeholder="Company or freelance" /></div><label className="block text-xs font-semibold" style={{ color: 'var(--text-secondary)' }}>About you<textarea rows={5} className="input-dark mt-1.5 resize-none" value={form.bio} onChange={(e) => update('bio', e.target.value)} placeholder="Your background and career goals…" /></label></section><section className="card p-6 space-y-4"><h2 className="font-bold text-white flex items-center gap-2"><Briefcase className="w-5 h-5 text-neon-cyan" /> Professional links</h2><div className="grid sm:grid-cols-2 gap-4"><Field label="LinkedIn URL" name="linkedin_url" placeholder="https://linkedin.com/in/…" /><Field label="GitHub URL" name="github_url" placeholder="https://github.com/…" /></div></section></div></div></div>;
}
