'use client';

import { useState } from 'react';
import { BriefcaseBusiness, Building2, ChevronDown, FileText, Globe2, Play, Plus, Sparkles, Target, X } from 'lucide-react';

type JobRole = 'fullstack' | 'backend' | 'frontend' | 'mobile' | 'devops' | 'system_design' | 'data_engineer' | 'ml_engineer';
type ExperienceLevel = 'junior' | 'mid' | 'senior';
interface InterviewConfig { jobRole: JobRole; experienceLevel: ExperienceLevel; techStack: string[]; mode: 'free'; targetMarket: 'local_palestine' | 'global_remote'; }
interface SetupWizardProps { onStart: (config: InterviewConfig) => void; }

const roles: { value: JobRole; label: string }[] = [{ value: 'fullstack', label: 'Full-Stack Developer' }, { value: 'frontend', label: 'Frontend Developer' }, { value: 'backend', label: 'Backend Developer' }, { value: 'mobile', label: 'Mobile Developer' }, { value: 'devops', label: 'DevOps / SRE' }, { value: 'system_design', label: 'System Design' }, { value: 'data_engineer', label: 'Data Engineer' }, { value: 'ml_engineer', label: 'ML Engineer' }];
const recommendedSkills = ['Next.js', 'React', 'TypeScript', 'Node.js', 'Git', 'GitHub', 'OOP', 'Data Structures', 'SQL', 'MongoDB', 'REST APIs', 'HTML', 'CSS', 'JavaScript'];

export default function SetupWizard({ onStart }: SetupWizardProps) {
  const [tab, setTab] = useState<'practice' | 'company'>('practice');
  const [jobRole, setJobRole] = useState<JobRole>('fullstack');
  const [experienceLevel, setExperienceLevel] = useState<ExperienceLevel>('mid');
  const [skills, setSkills] = useState(['Next.js', 'React', 'Git', 'GitHub', 'OOP', 'Data Structures', 'SQL', 'MongoDB', 'REST APIs', 'HTML', 'CSS', 'JavaScript']);
  const [skillInput, setSkillInput] = useState('');
  const [difficulty, setDifficulty] = useState('medium');
  const [market, setMarket] = useState<'local_palestine' | 'global_remote'>('global_remote');
  const [company, setCompany] = useState('');
  const [targetRole, setTargetRole] = useState('');
  const addSkill = (skill = skillInput.trim()) => { if (skill && !skills.includes(skill)) setSkills((current) => [...current, skill]); setSkillInput(''); };
  const removeSkill = (skill: string) => setSkills((current) => current.filter((item) => item !== skill));

  return <div className="card rounded-2xl overflow-hidden">
    <div className="flex border-b" style={{ borderColor: 'var(--border-subtle)' }}>
      {(['practice', 'company'] as const).map((name) => <button key={name} onClick={() => setTab(name)} className="px-5 py-3 text-sm font-semibold capitalize border-b-2 transition-colors" style={{ borderColor: tab === name ? 'var(--neon-cyan)' : 'transparent', color: tab === name ? 'var(--neon-cyan)' : 'var(--text-secondary)' }}>{name === 'practice' ? '⚡ Practice' : '◎ Company'}</button>)}
      <span className="ml-auto self-center mr-5 text-xs" style={{ color: 'var(--text-muted)' }}>Tailored interview setup</span>
    </div>
    <div className="p-5 sm:p-7 space-y-6">
      {tab === 'practice' ? <>
        <div className="grid md:grid-cols-2 gap-4"><Select label="Job Title / Role" required Icon={BriefcaseBusiness} value={jobRole} onChange={(value) => setJobRole(value as JobRole)} options={roles.map((role) => [role.value, role.label])} /><Select label="Interview Round" required Icon={Target} value="technical" onChange={() => {}} options={[["technical", "Technical Round"], ["behavioral", "Behavioral Round"], ["system", "System Design"]]} /></div>
        <div className="grid md:grid-cols-2 gap-4"><Select label="Experience Level" required Icon={BriefcaseBusiness} value={experienceLevel} onChange={(value) => setExperienceLevel(value as ExperienceLevel)} options={[["junior", "Junior · 0–2 years"], ["mid", "Mid Level · 2–5 years"], ["senior", "Senior · 5+ years"]]} /><div><Label text="Difficulty Level" /><div className="flex gap-2">{[['easy', 'Easy'], ['medium', 'Medium'], ['hard', 'Hard']].map(([value, label]) => <button key={value} onClick={() => setDifficulty(value)} className="flex-1 py-2 rounded-lg text-xs font-semibold" style={{ background: difficulty === value ? 'rgba(0,194,255,.14)' : 'rgba(255,255,255,.04)', border: `1px solid ${difficulty === value ? 'rgba(0,194,255,.4)' : 'var(--border-subtle)'}`, color: difficulty === value ? 'var(--neon-cyan)' : 'var(--text-secondary)' }}>{label}</button>)}</div></div></div>
        <SkillPicker skills={skills} input={skillInput} setInput={setSkillInput} add={addSkill} remove={removeSkill} />
        <ResumeCard />
        <details className="rounded-xl p-4" style={{ background: 'rgba(255,255,255,.025)', border: '1px solid var(--border-subtle)' }}><summary className="cursor-pointer text-sm font-semibold text-white flex items-center gap-2"><Sparkles className="w-4 h-4 text-neon-cyan" /> Customize your interview <span className="text-[10px] font-normal" style={{ color: 'var(--text-muted)' }}>Optional</span></summary><div className="flex flex-wrap gap-2 mt-4"><Pill text="Add job description" /><Pill text="English" /><Pill text="45 minutes" /><Pill text="Global remote" /></div></details>
      </> : <div className="space-y-5"><div><h2 className="text-lg font-bold text-white">Company research</h2><p className="text-sm mt-1">Add company context to generate more relevant interview questions.</p></div><div className="grid md:grid-cols-2 gap-4"><Input label="Company name" value={company} setValue={setCompany} placeholder="e.g. Google, Amazon, Meta" /><Input label="Target role" value={targetRole} setValue={setTargetRole} placeholder="e.g. Freelance Web Developer" /></div><div className="grid md:grid-cols-2 gap-4"><Select label="Target market" value={market} onChange={(value) => setMarket(value as typeof market)} options={[["global_remote", "Global / Remote"], ["local_palestine", "Palestinian local market"]]} /><Input label="Location" value="" setValue={() => {}} placeholder="e.g. Remote, Ramallah, Gaza" /></div><div className="rounded-xl p-4 text-sm" style={{ background: 'rgba(0,194,255,.06)', border: '1px solid rgba(0,194,255,.16)', color: 'var(--text-secondary)' }}>Company research will influence the examples and scenarios in your interview. You can continue without completing these fields.</div></div>}
      <button disabled={skills.length === 0} onClick={() => onStart({ jobRole, experienceLevel, techStack: skills, mode: 'free', targetMarket: market })} className="btn-cyan w-full justify-center py-3 text-sm disabled:opacity-50"><Play className="w-4 h-4" /> Start Interview</button>
    </div>
  </div>;
}
function Label({ text, required }: { text: string; required?: boolean }) { return <div className="text-xs font-semibold mb-1.5" style={{ color: 'var(--text-primary)' }}>{text} {required && <span className="ml-1 px-1.5 py-0.5 rounded-full text-[9px]" style={{ background: 'rgba(0,194,255,.12)', color: 'var(--neon-cyan)' }}>Required</span>}</div>; }
function Select({ label, value, onChange, options, required, Icon }: { label: string; value: string; onChange: (value: string) => void; options: string[][]; required?: boolean; Icon?: React.ElementType }) { return <div><Label text={label} required={required} /><div className="relative">{Icon && <Icon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4" style={{ color: 'var(--text-muted)' }} />}<select value={value} onChange={(e) => onChange(e.target.value)} className="input-dark appearance-none pr-9" style={{ paddingLeft: Icon ? '2.4rem' : undefined }}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select><ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 pointer-events-none" style={{ color: 'var(--text-muted)' }} /></div></div>; }
function Input({ label, value, setValue, placeholder }: { label: string; value: string; setValue: (value: string) => void; placeholder: string }) { return <div><Label text={label} /><input className="input-dark" value={value} onChange={(e) => setValue(e.target.value)} placeholder={placeholder} /></div>; }
function SkillPicker({ skills, input, setInput, add, remove }: { skills: string[]; input: string; setInput: (value: string) => void; add: (value?: string) => void; remove: (value: string) => void }) { return <div><Label text="Key Skills" required /><p className="text-xs mb-2">Questions focus on these skills, not unrelated technologies.</p><div className="rounded-xl p-2 flex flex-wrap gap-1.5" style={{ border: '1px solid var(--border-medium)', background: 'rgba(255,255,255,.02)' }}>{skills.map((skill) => <button onClick={() => remove(skill)} key={skill} className="px-2 py-1 rounded-md text-[11px] font-semibold flex items-center gap-1" style={{ background: 'rgba(245,158,11,.14)', color: 'var(--text-primary)' }}>{skill}<X className="w-3 h-3" /></button>)}<input value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); add(); } }} className="bg-transparent outline-none text-xs min-w-24 flex-1 px-1" placeholder="Add more…" /></div><div className="flex flex-wrap gap-2 mt-2"><button onClick={() => add()} className="btn-ghost text-xs py-1.5 px-3"><Plus className="w-3 h-3" /> Add skill</button>{recommendedSkills.filter((skill) => !skills.includes(skill)).slice(0, 4).map((skill) => <button key={skill} onClick={() => add(skill)} className="text-xs px-2 py-1 rounded-md" style={{ background: 'rgba(255,255,255,.05)', color: 'var(--text-secondary)' }}>+ {skill}</button>)}</div></div>; }
function ResumeCard() { return <div><Label text="Resume" /><div className="rounded-xl p-4 flex items-center gap-3" style={{ background: 'rgba(0,194,255,.045)', border: '1px solid rgba(0,194,255,.25)' }}><div className="w-9 h-9 rounded-lg flex items-center justify-center" style={{ background: 'rgba(0,194,255,.12)' }}><FileText className="w-4 h-4 text-neon-cyan" /></div><div className="flex-1"><p className="text-sm font-semibold text-white">Add your resume</p><p className="text-xs">Optional — questions can be tailored to your experience.</p></div><label className="btn-ghost text-xs cursor-pointer">Choose file<input type="file" accept="application/pdf" className="hidden" /></label></div></div>; }
function Pill({ text }: { text: string }) { return <span className="text-xs px-2 py-1 rounded-full" style={{ background: 'rgba(255,255,255,.06)', color: 'var(--text-secondary)' }}>{text}</span>; }
